def comparisonoprators():
    n1=int(input("Enter the value of n1:"))
    n2=int(input("Enter the value of n2:"))
    n3=int(input("Enter the value of n3:"))
    print("n1==n3:",(n1==n3))
    print("n1>n3:",(n1>n3))
    print("n1<n3:",(n1<n3))
    print("n1<=n3:",(n1<=n3))
    print("n1>=n3:",(n1>=n3))
    print("n1!=n3:",(n1!=n3))
comparisonoprators()
